/// <reference types="astro/client" />
/// <reference path="../.astro/types.d.ts" />

// Type definitions for environment variables and global types
declare namespace App {
  interface Locals {}
}

// Content collection types will be auto-generated by Astro
declare module 'astro:content' {
  interface ContentEntryMap {}
  interface DataEntryMap {}
}